name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build artifacts
        run: make compile
        shell: bash
      - name: version
        run: echo "::set-output name=version::$(./otter version)"
        id: version
      - name: build artifacts
        run: make compile_all
        shell: bash
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: upload linux64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/otter-linux-amd64
          asset_name: otter-linux-amd64
          asset_content_type: application/x-executable
      - name: upload mac intel64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/otter-mac-amd64
          asset_name: otter-mac-amd64
          asset_content_type: application/x-mach-binary
